include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    sort_constructors_first: ignore
