name: family_color_picker
description: "Family Color Picker"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/og-image.png
